declare namespace Market {
  export type PairMarketHistory = {
    exchangeId: string;
    exchangeName: string;
    id: string;
    symbol: string;
    wsName: string;
    price: string;
    lastPrice: string;
    change1h: string;
    change4h: string;
    change24: string;
    change1hPercent: string;
    change4hPercent: string;
    change24Percent: string;
    roi1mo: string;
    roi1y: string;
    marketcap: string;
  };
  export type TradingPair = {
    baseAsset: string;
    baseCurrencyIcon: string;
    currencyId: string;
    exchangeId: string;
    exchangeName: string;
    id: string;
    platform: string;
    platformCurrencyId: string;
    quoteAsset: string;
    status: number;
    symbol: string;
    type: string;
    wsName: string;
    nature: string;
    fullName?: string;
  };
  export type PairMarket = {
    E: number;
    P: string;
    c: number;
    m: string;
    p: number;
    y: string;
  };
  export type TopGainer = {
    baseAsset: string;
    change24h: number;
    change24hPercent: number;
    changePercentSort: string;
    currencyAliasName: string;
    currencyId: string;
    currencyName: string;
    currencyFullName: string;
    currencySort: string;
    iconUrl: string;
    quoteAsset: string;
    symbolAmt: number;
    symbolId: string;
    symbolName: string;
    wsname: string;
    marketCap: string;
    symbolName: string;
    wsname: string;
    baseAsset: string;
    quoteAsset: string;
    exchangeName: string;
    exchangeRate?: string;
    currencyName: string;
    currencyAliasName: string;
  };
  export type CurrencyDoVO = {
    aliasName: string;
    avMarketcapSort: number;
    categoriesAtomList: string[];
    contractAddress: string;
    currencyDataDoVO: null;
    fullName: string;
    iconUrl: string;
    id: string;
    indexStatus: number;
    markCondition: number;
    matchSet: string;
    name: string;
    platformCurrencyDoVOS: null;
    pricePrecision: null;
    processStatus: null;
    sort: number;
    status: number;
    symbolDoVO: null;
    updateTime: string;
  };
}
