declare namespace Research {
  export type Post = {
    title: string;
    id: string;
    author: string;
    category: number;
    content: string;
    source: string;
    createTime: string;
    realiseTime: string;
    sourceLink: string;
    originalContent: string;
    originalContent2: string;
    sector: string;
    platName: string;
    pushTime: string;
    contentNum: string;
    isAiGeneration: number;
    originalContent: string;
    originalContent2: string;
    isAuth: number;
    isOfficial: 0 | 1 | undefined;
    authorAvatar: string;
    transferStatus: 0 | 1;
    weight: number;
    generateWay: number;
    coverPicture: string;
    sourceDescription: string;
    originalLanguage: 1 | 2;
    sourcePlatId: string;
    transferTitle: string;
    transferOriginalContent: string;
    transferContent: string;
    transferTraditionalTitle: string;
    transferTraditionalContent: string;
    transferTraditionalOriginalContent: string;
    seoSlug?: string;
    seoTitle?: string;
    transferSeoTitle?: string;
    transferTraditionalSeoTitle?: string;
    seoMeta?: string;
    transferSeoMeta?: string;
    transferTraditionalSeoMeta?: string;
    matchedCurrencies?: {
      count: number;
      fullName: string;
      iconUrl?: string;
      name: string;
      id: string;
    }[];
  };
  export type ClusterNews = {
    id: string;
    clusterNewsId: string;
    content: string;
    creator: string;
    entityList: string;
    matchedCurrencies: string;
    modifier: string;
    sector: string;
    status: number;
    title: string;
    weight: number;
    createTime: string;
    informationDoVos: Post[];
    contentInformationSourceList: ContentInformationSource[];
  };
  export type HotNewsMatchedCurrency = {
    aliasName: string;
    count: number;
    fullName: string;
    iconUrl: string;
    id: number;
    name: string;
  };
  export type ContentInformationSource = {
    category: number;
    creator: string;
    id: string;
    isAuth: number;
    isOfficial: number;
    language: 1;
    lastUpdateTime: string;
    logo: string;
    modifier: string;
    newsRemovedRate: number;
    newsTotalCount: number;
    rssUrl: null;
    sourceDescription: null;
    sourceName: string;
    status: number;
    type: string;
    weight: number;
  };
  export type Curated = {
    id: string;
    informationDoVo?: Post;
    status: number;
    subjectId: string;
  };
}
